# Using the WRDS Platform for Compustat Data
Src Documentation:
    - https://wrds-www.wharton.upenn.edu/documents/1443/wrds_connection.html
    - https://wrds-www.wharton.upenn.edu/pages/support/programming-wrds/programming-python/querying-wrds-data-python/
    - https://pypi.org/project/wrds/

In [2]:
import wrds
# Sets up the connection, creates a pgpass file
conn = wrds.Connection()

WRDS recommends setting up a .pgpass file.
Created .pgpass file successfully.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

In [3]:
conn.list_libraries().sort()
#type(conn.list_libraries())

In [5]:
# List all datasets within a given library
conn.list_tables(library='comp_na_daily_all')

['aco_amda',
 'aco_imda',
 'aco_indfnta',
 'aco_indfntq',
 'aco_indfntytd',
 'aco_indsta',
 'aco_indstq',
 'aco_indstytd',
 'aco_notesa',
 'aco_notesq',
 'aco_notessa',
 'aco_notesytd',
 'aco_pnfnda',
 'aco_pnfndq',
 'aco_pnfndytd',
 'aco_pnfnta',
 'aco_pnfntq',
 'aco_pnfntytd',
 'aco_transa',
 'aco_transq',
 'aco_transsa',
 'aco_transytd',
 'adsprate',
 'asec_amda',
 'asec_imda',
 'asec_notesa',
 'asec_notesq',
 'asec_transa',
 'asec_transq',
 'chars',
 'co_aacctchg',
 'co_aaudit',
 'co_adesind',
 'co_adjfact',
 'co_afnd1',
 'co_afnd2',
 'co_afnddc1',
 'co_afnddc2',
 'co_afntind1',
 'co_afntind2',
 'co_ainvval',
 'co_amkt',
 'co_busdescl',
 'co_cotype',
 'co_filedate',
 'co_fortune',
 'co_hgic',
 'co_iacctchg',
 'co_iaudit',
 'co_idesind',
 'co_ifndq',
 'co_ifndsa',
 'co_ifndytd',
 'co_ifntq',
 'co_ifntsa',
 'co_ifntytd',
 'co_imkt',
 'co_industry',
 'co_ipcd',
 'co_mthly',
 'co_offtitl',
 'company',
 'currency',
 'dd_group',
 'dd_group_xref',
 'dd_item',
 'dd_package',
 'ecind_desc',
 'ecind_mth',
 'exrt_dly',
 'exrt_mth',
 'funda',
 'funda_fncd',
 'fundq',
 'fundq_fncd',
 'idx_ann',
 'idx_anndes',
 'idx_daily',
 'idx_index',
 'idx_mth',
 'idx_qrt',
 'idx_qrtdes',
 'idxcst_his',
 'io_qaggregate',
 'io_qbuysell',
 'io_qchanges',
 'io_qfloatadj',
 'io_qholders',
 'it_mbuysell',
 'it_msummary',
 'it_r_rltn',
 'names',
 'names_aco_indsta',
 'names_aco_indstq',
 'names_aco_pnfnda',
 'names_aco_pnfndq',
 'names_adsprate',
 'names_ix',
 'names_ix_cst',
 'names_seg',
 'namesd',
 'namesm',
 'namesq',
 'r_accstd',
 'r_acqmeth',
 'r_auditors',
 'r_auopic',
 'r_balpres',
 'r_cf_formt',
 'r_co_status',
 'r_coindpre',
 'r_compstat',
 'r_consol',
 'r_country',
 'r_cstclscd',
 'r_datacode',
 'r_datafmt',
 'r_divtaxmarker',
 'r_docsrce',
 'r_ex_codes',
 'r_exchgtier',
 'r_exrt_typ',
 'r_fndfntcd',
 'r_footnts',
 'r_foricd',
 'r_giccd',
 'r_hcalendr',
 'r_idxclscd',
 'r_inactvcd',
 'r_incstats',
 'r_indfmt',
 'r_indsec',
 'r_invval',
 'r_issuetyp',
 'r_majidxcl',
 'r_mic_codes',
 'r_naiccd',
 'r_notetype',
 'r_ntsubtype',
 'r_offcrso',
 'r_ogmethod',
 'r_opinions',
 'r_prc_stat',
 'r_qsrcdoc',
 'r_sec_stat',
 'r_secannfn',
 'r_sectors',
 'r_siccd',
 'r_spiicd',
 'r_spmicd',
 'r_statalrt',
 'r_states',
 'r_stko',
 'r_titles',
 'r_updates',
 'sec_adesind',
 'sec_adjfact',
 'sec_afnd',
 'sec_afnddc',
 'sec_afnt',
 'sec_divid',
 'sec_dprc',
 'sec_dtrt',
 'sec_history',
 'sec_idesind',
 'sec_ifnd',
 'sec_ifnt',
 'sec_mdivfn',
 'sec_mshare',
 'sec_msptfn',
 'sec_mth',
 'sec_mthdiv',
 'sec_mthprc',
 'sec_mthspt',
 'sec_mthtrt',
 'sec_shortint',
 'sec_spind',
 'sec_split',
 'secd',
 'secm',
 'security',
 'sedolgvkey',
 'seg_ann',
 'seg_annfund',
 'seg_customer',
 'seg_geo',
 'seg_naics',
 'seg_product',
 'seg_type',
 'spidx_cst',
 'spind',
 'spind_dly',
 'spind_mth',
 'wrds_ratios',
 'wrds_seg_customer',
 'wrds_seg_geo',
 'wrds_seg_product',
 'wrds_segmerged',
 'xfl_column',
 'xfl_table']

5. Query Data from WRDS Server
- get_table() method
- straightforward if getting data from one single dataset
- specify which library/database and table/dataset to "get"
- can slice data by:
        number of rows
        column names

In [11]:
# Sample to query data from WRDS server

In [12]:
# Extract first 5 obs from comp.company

company = conn.get_table(library='comp', table='company', obs=5)
company.shape

(5, 39)

In [13]:
company

,conm,gvkey,add1,add2,add3,add4,addzip,busdesc,cik,city,...,priusa,sic,spcindcd,spcseccd,spcsrc,state,stko,weburl,dldte,ipodate
0,A & E PLASTIK PAK INC,001000,None,None,None,None,None,A & E Plastik Pak Inc. is a commodity chemical...,None,None,...,01,3089,325,978,None,None,0,None,1978-06-30,None
1,A & M FOOD SERVICES INC,001001,1924 South Utica Avenue,None,None,None,94104,None,0000723576,Tulsa,...,01,5812,420,978,None,OK,0,None,1986-07-31,None
2,AAI CORP,001002,124 Industry Lane,None,None,None,21030-0126,"Textron Systems Corporation designs, develops,...",0001306124,Hunt Valley,...,01,3825,230,940,None,MD,0,www.textronsystems.com,1977-03-31,None
3,A.A. IMPORTING CO INC,001003,7700 Hall Street,None,None,None,63125,"A.A. Importing Company, Inc. designs, manufact...",0000730052,St. Louis,...,01,5712,449,976,None,MO,3,www.aaimporting.com,1992-04-30,None
4,AAR CORP,001004,"One AAR Place, 1100 North Wood Dale Road",None,None,None,60191,AAR Corp. provides products and services to co...,0000001750,Wood Dale,...,01,5080,110,925,B,IL,0,www.aarcorp.com,None,1972-04-24

In [ ]:
# Uses permno sample
apple = conn.raw_sql("""select permno, date, prc, ret, shrout 
                        from crsp.msf 
                        where permno = 14593
                        and date>='01/01/2019'""", 
                     date_cols=['date'])
apple

In [15]:
# Table Values:
'''
    tic : ticker
    busdesc : business description
    cusip : cusip
    loc : current iso country code (HQ)
    gind : gics industries
    gsector : gics sector
    div : dividend or divd : cash dividends daily
    prccd : price close daily
    prchd : price high daily
    prcld : price low daily
    prcod : price open daily
    trfd : daily total return factor
'''
apple = conn.raw_sql("""select tic
                        from comp_na_daily_all.security 
                        where tic = 'AAPL'
                        """, 
                     date_cols=['date'])

In [12]:
apple

    tic
0  AAPL